export const PREFECTURE = [
	"Tokyo",
	"Kanagawa",
	"Saitama",
	"Chiba",
	"Shizuoka",
	"Ibaraki",
	"Tochigi",
	"Gunma",
	"Yamanashi",
	"Nagano",
	"Niigata",
	"Fukushima",
	"Osaka",
	"Other"
];

export const PREFECTURE_CITIES = {
	Tokyo: [
		"Adachi",
		"Arakawa",
		"Bunkyō",
		"Chiyoda",
		"Chūō",
		"Edogawa",
		"Itabashi",
		"Katsushika",
		"Kita",
		"Kōtō",
		"Meguro",
		"Minato",
		"Nakano",
		"Nerima",
		"Ōta",
		"Setagaya",
		"Shibuya",
		"Shinagawa",
		"Shinjuku",
		"Suginami",
		"Sumida",
		"Taitō",
		"Toshima"
	],
	Kanagawa: [
		"Yokohama",
		"Kawasaki",
		"Sagamihara",
		"Yokosuka",
		"Fujisawa",
		"Kamakura",
		"Odawara",
		"Chigasaki",
		"Zushi",
		"Atsugi",
		"Yamato",
		"Ebina",
		"Isehara",
		"Zama",
		"Miura",
		"Hayama",
		"Yamato",
		"Fujisawa",
		"Kamakura",
		"Minamiashigara"
	],
	Saitama: [
		"Saitama",
		"Kawaguchi",
		"Kumagaya",
		"Tokorozawa",
		"Kawagoe",
		"Kasukabe",
		"Shiki",
		"Hanno",
		"Warabi",
		"Omiya"
	],
	Chiba: [
		"Chiba",
		"Funabashi",
		"Ichikawa",
		"Kashiwa",
		"Narashino",
		"Urayasu",
		"Yachiyo",
		"Matsudo",
		"Nagareyama",
		"Mobara"
	],
	Shizuoka: ["Shizuoka", "Hamamatsu", "Numazu", "Fujieda", "Iwata", "Yaizu", "Kakegawa", "Shimada", "Kosai", "Atami"],
	Ibaraki: [
		"Mito",
		"Tsukuba",
		"Hitachi",
		"Tsuchiura",
		"Kashima",
		"Hitachiota",
		"Ryugasaki",
		"Koga",
		"Inashiki",
		"Shimotsuma"
	],
	Tochigi: ["Utsunomiya", "Ashikaga", "Kanuma", "Oyama", "Nikkō", "Sano", "Otawara", "Mooka", "Tochigi", "Yaita"],
	Gunma: ["Maebashi", "Takasaki", "Isesaki", "Ota", "Kiryu", "Tatebayashi", "Fujioka", "Annaka", "Tomakomai", "Numata"],
	Yamanashi: ["Kofu", "Fuefuki", "Yamanashi", "Kai", "Isawa", "Minobu", "Nirasaki", "Enzan", "Tsuru", "Hokuto"],
	Nagano: ["Nagano", "Matsumoto", "Ueda", "Iida", "Suwa", "Chino", "Komoro", "Saku", "Nakano", "Suzaka"],
	Niigata: ["Niigata", "Nagaoka", "Jōetsu", "Kashiwazaki", "Sanjō", "Tsubame", "Shibata", "Gosen", "Murakami", "Sado"],
	Fukushima: [
		"Fukushima",
		"Aizuwakamatsu",
		"Kōriyama",
		"Iwaki",
		"Shirakawa",
		"Sukagawa",
		"Minamisoma",
		"Date",
		"Nihonmatsu",
		"Motomiya"
	],
	Osaka: [
		"Osaka",
		"Sakai",
		"Higashiosaka",
		"Takatsuki",
		"Suita",
		"Kishiwada",
		"Neyagawa",
		"Kadoma",
		"Moriguchi",
		"Ikeda"
	]
};
